repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.10.0  # Use the latest version of Black
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest version of Flake8
    hooks:
      - id: flake8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
      - id: check-added-large-files
        args: [--maxkb=1024]  # Allow files up to 1 MB